version: 0.2

phases:
  IntegrationTest:
    commands:
      - npm install
      - npm run test
  Deploy:
    commands:
      - npm run sls -- deploy -s $STAGE -r $REGION
  AcceptanceTest:
    commands:
      - npm run acceptance
